[app]
name = "gin-web"
mode = "debug"
port = "3333"

[database]
host = "localhost"
port = "3306"
user = "root"
password = "123456"
database = "dev_go"

[jwt]
secret_key = "gin-web"
token_expire = 24 # 单位小时
