basePath: /api
definitions:
  response.Response:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 数据内容
      message:
        description: 提示信息
        type: string
    type: object
  services.LoginParams:
    properties:
      account:
        description: 账号 邮箱/手机号/用户名
        type: string
      password:
        description: 密码 6-16位
        type: string
    required:
    - account
    - password
    type: object
  services.RegisterParams:
    properties:
      account:
        description: 账号 邮箱/手机号/用户名
        type: string
      password:
        description: 密码 6-16位
        type: string
    required:
    - account
    - password
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3333
info:
  contact:
    email: 1227379879@qq.com
    name: North
  description: 权限管理系统swagger api介绍
  termsOfService: http://swagger.io/terms/
  title: 权限管理系统
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/services.LoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 登录
      tags:
      - 用户
  /user/register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/services.RegisterParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 注册
      tags:
      - 用户
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
